name: "Restart PM2 service Action"
author: fcocea
description: "Restart the remote pm2 service upon detecting changes to your repository"

inputs:
  SSH_HOST:
    description: "SSH IP address of the remote server"
    required: true
  SSH_PORT:
    description: "SSH Port of the remote server"
    required: true
    default: 22
  SSH_USER:
    description: "SSH Username for connecting to the remote server"
    required: true
  SSH_PASS:
    description: "SSH Password for connecting to the remote server"
    required: true
  FOLDER:
    description: "Folder where the pm2 service is located"
    required: true
  PM2_SERVICE:
    description: "Name of the pm2 service"
    required: true
  REPO_BRANCH:
    description: "Branch of the repository"
    required: false
    default: "main"
runs:
  using: "docker"
  image: "Dockerfile"
  env: 
    SSH_HOST: ${{ inputs.SSH_HOST }}
    SSH_PORT: ${{ inputs.SSH_PORT }}
    SSH_USER: ${{ inputs.SSH_USER }}
    SSH_PASS: ${{ inputs.SSH_PASS }}
    FOLDER: ${{ inputs.FOLDER }}
    PM2_SERVICE: ${{ inputs.PM2_SERVICE }}
    REPO_BRANCH: ${{ inputs.REPO_BRANCH }}
branding:
  icon: "terminal"
  color: "gray-dark"